### ISSUE TITLE
Code development - QR Code

### ISSUE THREAD

**Issue by saravanan19** [SidHeg/se17-teamD#15]
- Study APIs
- Develop code 
- test the features

**Comment by saravanan19** [comment]
I have created the frontend skeleton code. You may pull the code and test it in your mobile phone. Have left place holder for QRCode code. Your code need to be inserted into the btnQRCodeOnClicklistener.

**Comment by mohits19** [comment]
Completed basic QR code generation from text and scanning QR code.
