### ISSUE TITLE
API availability and Feasibility Check. 

### ISSUE THREAD

**Issue by saravanan19** [SidHeg/se17-teamD#17]
- QR Code
- GPS
- NFC 

Also analyse the NFC hardware dependencies

**Comment by SidHeg** [comment]
Below is the link to an Adriod document regarding using GPS.
https://developer.android.com/guide/topics/location/strategies.html

**Comment by saravanan19** [comment]
NFC Reader/ Writer mode can be used.
Professor can write data onto the NFC tag.
Student can read the tag using their phone.
Android provides APIs to support Read and Write operations using the following classes
Ndef Message,
Ndef Record,
Tag,
NFC Adapter,
NFC Event,
NFC Manager.

And, following interfaces

NfcAdapter.CreateBeamUrisCallback	 
NfcAdapter.CreateNdefMessageCallback	
NfcAdapter.OnNdefPushCompleteCallback	
NfcAdapter.OnTagRemovedListener	
NfcAdapter.ReaderCallback

Source: https://developer.android.com/reference/android/nfc/package-summary.html

**Comment by mohits19** [comment]
Android API for Barcode scanners(including QR code) : https://developers.google.com/vision/android/barcodes-overview

The documentation for a web API allows to generate QR codes for any given text and scan QR codes is given at http://goqr.me/api/
Example to create QR codes: https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=Course: CSC 510 Instructor: Tim Menzies Date and Time: 02/14/2017 16:30-17:45 Passcode: xRghYl

There is an open source barcode image processing library at https://github.com/zxing/zxing which is implemented in Java and available in Android.
