### ISSUE TITLE
comment: feb deliverables look interesting

### ISSUE THREAD

**Issue by timm** [SidHeg/se17-teamD#36]
do i understand your architecture? everyone talks to the same DB back end?

re the DB:

- `student` and `professor` are probably both `roles` of `Person`
- a `student`'s `courses` are probably a bridge relationship between `Person` and `Subject`

thanks for the work. i look forward to the demon, after the spring break.

**Comment by saravanan19** [comment]
Yes. Everyone talks to the same back end database. 

And, we will make the necessary changes to the db.

**Comment by timm** [comment]
dont feel obliged to make that change.. just if it make sense to you
